# https://realm.github.io/SwiftLint/rule-directory.html

disabled_rules:
  - identifier_name
  - control_statement
  - return_arrow_whitespace
opt_in_rules:
  - empty_count

included:
  - Notes
excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
analyzer_rules:
  - explicit_self


force_cast: warning
force_try:
  severity: warning

line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
  
trailing_whitespace:
  ignores_empty_lines: true

# reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
